<a href="https://colab.research.google.com/github/NaqashZulfiqar/Python-Learning/blob/main/PMYSD-P-B-3/NumpyPratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing NumPy

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


2. NumPy Basics

1. Performance: NumPy is Faster than Lists

In [ ]:
import numpy as np
import time

#using Python List
size = 1_000_000
py_list = list(range(size))

start_time = time.time()
sum_py = sum(py_list)
end_time = time.time()

print("Sum using Python List : ",sum_py)
print("Time Taken : ",end_time - start_time ,"Seconds")

print("\n ***** Numpy *****")
#using Numpy Array
arr = np.arange(size)
start_time = time.time();
sum_np = np.sum(arr)
end_time = time.time()

print("\n Sum Using Numpy : ",sum_np)
print("Time Taken : ", end_time - start_time,"Seconds")



Sum using Python List :  499999500000
Time Taken :  0.01141214370727539 Seconds

 ***** Numpy *****

 Sum Using Numpy :  499999500000
Time Taken :  0.001390695571899414 Seconds


2. Memory Efficiency: NumPy Uses Less Memory

In [ ]:
import sys
# Python list memory usage
py_list = list(range(1000))
print("Python list size : ",sys.getsizeof(py_list) * len(py_list),"bytes")

# Numpy array memory usage
np_array = np.arange(1000)
print("Numpy array size : ",np_array.nbytes,"bytes")

Python list size :  8056000 bytes
Numpy array size :  8000 bytes


3. Vectorized Operations: NumPy is More Efficient

In [ ]:
py_list = [1,2,3,4,5]
py_result = [X * 2 for X in py_list]
print("Python :",py_result)

#Numpy
np_array = np.array([1,2,3,4,5])
np_result = np_array * 2
print("Numpy :",np_result)

Python : [2, 4, 6, 8, 10]
Numpy : [ 2  4  6  8 10]


Creating NumPy Arrays

1. Using np.array() – Convert a List to an Array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


2. Using np.zeros() – Create an Array of Zeros

In [ ]:
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Using np.ones() – Create an Array of Ones

In [ ]:
arr = np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Using np.arange() – Create a Range of Values

In [ ]:
arr = np.arange(1,10,2) # Start at 1, go up to 10, step 2
print(arr)

arr1 = np.arange(1,20,3) # Start at 1, go up to 20, step 3
print(arr1)

[1 3 5 7 9]
[ 1  4  7 10 13 16 19]


5. Using np.linspace() – Create Evenly Spaced Values

In [ ]:
arr = np.linspace(0,5,10) # 10 values between 0 and 5
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


Data Types in NumPy (dtype)

In [ ]:
arr  = np.array([1,2,3])
print(arr.dtype)

int64


Specifying a Data Type

In [3]:
import numpy as np
arr = np.array([1,2,3],dtype=np.float32)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


Shape and Dimensions of Arrays

1. .shape – Get the Shape of an Array

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) #Returns a tuple representing the number of rows and columns.
print(arr.ndim) #Get the Number of Dimensions ,2(2D Array)
print(arr.size) #Total number of elements in array

(2, 3)
2
6


Reshaping and Flattening Arrays

1. .reshape() – Change the Shape of an Array

In [12]:
arr = np.arange(1,7)
reshape_arr = arr.reshape(2,3)
print(reshape_arr)

flat_arr = reshape_arr.flatten() #Convert a Multi-Dimensional Array into 1D
print(flat_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


3. NumPy Indexing & Slicing

1. Accessing Elements in 1D Arrays

In [13]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1])
print(arr[-1])

10
20
50


2. Accessing Elements in 2D Arrays (Matrix Indexing)

In [17]:
arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr_2d[0,0]) # 1(First row first column)
print(arr_2d[1,2]) # 6(Second row third coloum)
print(arr_2d[-1,-1]) # 9(Last row last column)

1
6
9


3. Accessing Elements in 3D Arrays

In [22]:
arr_3d = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print(arr_3d[0,1,2]) # 6(First depth second row third column)
print(arr_3d[1,0,1]) # 8(Second depth, first row second column)

6
8


Slicing NumPy Arrays (: operator)

1. Slicing 1D Arrays

In [29]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[1:5]) #[20,30,40,50]
print(arr[:4]) #[10 20 30 40]
print(arr[2:]) #[30 40 50 60 70]
print(arr[::2]) #[10 30 50 70] Every 2nd element
print(arr[::-1]) #[70 60 50 40 30 20 10] Reversed array

[20 30 40 50]
[10 20 30 40]
[30 40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


2. Slicing 2D Arrays

In [34]:
arr_2d = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])
print(arr_2d[0:2,1:3]) # (Rows 0-1,column 1-2)
print(arr_2d[:,2]) #All rows 3rd column
print(arr_2d[1,:]) #2nd row all column

[[2 3]
 [6 7]]
[ 3  7 11]
[5 6 7 8]


3. Slicing 3D Arrays

In [37]:
arr_3d = np.array([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]]])
print(arr_3d[:,:,1]) #All depth all rows 2nd column

[[ 2  5]
 [ 8 11]]


Boolean Masking and Filtering

1. Using Boolean Conditions

In [40]:
arr = np.array([10,20,30,40,50])
mask = arr > 25
print(mask)
print(arr[mask])

#2. Direct Condition in Indexing
print(arr[arr < 40]) #All elements < 40

[False False  True  True  True]
[30 40 50]
[10 20 30]


3. Applying Conditions on 2D Arrays

In [42]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[arr_2d % 2 == 0]) #only Even numbers

[2 4 6 8]
