<a href="https://colab.research.google.com/github/NaqashZulfiqar/Python-Learning/blob/main/PMYSD-P-B-3/Numpy2ndClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[-1])

10
20
30
50


Accessing elements in 2D Arrays (Matrix Indexing)

In [10]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[0][0])
print(arr_2d[1][3])

1


IndexError: index 3 is out of bounds for axis 0 with size 3

Accessing elements in 3D array

In [5]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr_3d[0][1][2])
#print(arr_3d[1,0,1])

6


IndexError: index 1 is out of bounds for axis 0 with size 1

In [6]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[1:5])

[20 30 40 50]


In [8]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d[0:2,1:3]) #here 0:2 mean first row and second row
print(arr_2d[:,2])
print(arr_2d[1,:])
print(arr_2d[::])

[[2 3]
 [6 7]]
[ 3  7 11]
[5 6 7 8]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slicing 3D Array

In [9]:
arr_3d = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print(arr_3d[:,:,1])

[[ 2  5]
 [ 8 11]]
