<a href="https://colab.research.google.com/github/NaqashZulfiqar/Python-Learning/blob/main/PMYSD-P-B-3/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
import numpy as np
import time

#Using Python List
size = 1_000_000 #1 million
py_list = list(range(size))
start_time = time.time()
sum_py = sum(py_list)
end_time = time.time()
print("Sm using Python list : ", sum_py)
print("Time Taken :",end_time - start_time,"seconds")

#Using Numpy array
np_array = np.arange(size)

start_time = time.time()
sum_py = np.sum(np_array)
end_time = time.time()

print("\nSum using NumPy array: ",sum_py)
print("Time Taken : ", end_time - start_time,"Seconds")

Sm using Python list :  499999500000
Time Taken : 0.01117086410522461 seconds

Sum using NumPy array:  499999500000
Time Taken :  0.001070261001586914 Seconds


2. Memory Efficiency: NumPy Uses Less Memory

In [6]:
import sys

#Python List memory usage
py_list = list(range(1000))
print("Python list size:",sys.getsizeof(py_list)* len(py_list),"bytes")

#NumPy array memory usage
np_array = np.arange(1000)
print("NumPy array ize:",np_array.nbytes,"bytes")

Python list size: 8056000 bytes
NumPy array ize: 8000 bytes


3. Vectorized Operations: NumPy is More Efficient

In [7]:
py_list = [1,2,3,4,5]
py_result = [X * 2 for X in py_list]
print(py_result)

[2, 4, 6, 8, 10]


In [8]:
np_array = np.array([1,2,3,4,5])
np_result = np_array * 2
print(np_result)

[ 2  4  6  8 10]


2. Using np.zeros() – Create an Array of Zeros

In [9]:
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Using np.ones() – Create an Array of Ones

In [10]:
ones_array = np.ones((2,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Using np.arange() – Create a Range of Values

In [12]:
arr = np.arange(1,10,2) #Here 1 is start, 10 is End and 2 is increment
print(arr)

[1 3 5 7 9]


5. Using np.linspace() – Create Evenly Spaced Values

In [13]:
arr = np.linspace(0,5,10)
print(arr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
