<a href="https://colab.research.google.com/github/NaqashZulfiqar/Python-Learning/blob/main/PMYSD-P-B-3/Numpy3rdclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
arr = np.array([10,20,30,40,50])
mask = arr > 5
print(mask)
print(arr[mask])


[ True  True  True  True  True]
[10 20 30 40 50]


In [ ]:
arr = np.array()

In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d[arr_2d % 2 == 0])

[2 4 6 8]


4. NumPy Operations

In [6]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 **2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [9]:
arr = np.array([10,20,30,40])
print(arr + 5)
print(arr * 2)
print(arr -5)

[15 25 35 45]
[20 40 60 80]
[ 5 15 25 35]


Example 2: Broadcasting in Different Shaped Arrays

In [10]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([10,20,30])
print(arr1 + arr2)

[[11 22 33]
 [14 25 36]]


1. Summation: np.sum()

In [13]:
arr =np.array([[1,2,3],
              [4,5,6]])
print(np.sum(arr)) #sum of all element
print(np.sum(arr, axis=0)) #Solumn wise
print(np.sum(arr, axis=1))# Row wise

print(np.mean(arr)) #Mean of All Elements

21
[5 7 9]
[ 6 15]
3.5


3. Standard Deviation & Variance

In [14]:
print(np.std(arr))
print(np.var(arr))

1.707825127659933
2.9166666666666665


For 2D arrays:

In [17]:
arr_2d = np.array([[30,10,50],
                   [20,40,60]])
print(np.sort(arr_2d,axis=0))
print(np.sort(arr_2d,axis=1))

print(np.min(arr_2d)) #Return value
print(np.argmin(arr_2d))# Return Index

[[20 10 50]
 [30 40 60]]
[[10 30 50]
 [20 40 60]]
10
1


5. Linear Algebra with NumPy

In [21]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])
result = np.dot(A,B) # do like paper work
print(result)
print("****")
r = A@B
print(r)

[[19 22]
 [43 50]]
****
[[19 22]
 [43 50]]


4. Inverse of a Matrix (np.linalg.inv())

In [23]:
A = np.array([[4,7],
              [2,6]])
A_inv = np.linalg.inv(A)
print(A_inv)

print(A @ A_inv)

#point to be remenbered
# 1: matrix should not be

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


5. Eigenvalues and Eigenvectors (np.linalg.eig())

In [24]:
A = np.array([[4,-2],
              [1,1]])
eignvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues :",eignvalues)
print("Eigenvectors : \n",eigenvectors)

Eigenvalues : [3. 2.]
Eigenvectors : 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Dice

In [26]:
import numpy as np
roll = np.random.randint(1,7,size = 1000)
print(roll)
count = np.bincount(roll)[1:]
print(count)

[1 3 4 1 1 5 4 4 4 5 4 3 2 2 6 6 4 5 2 4 4 5 3 2 6 3 2 1 5 5 2 4 2 4 6 4 2
 2 1 5 3 6 5 2 1 6 3 6 6 5 6 3 1 3 4 5 5 1 4 6 1 6 2 5 5 6 3 4 1 5 4 3 1 2
 2 6 3 3 3 2 5 4 5 5 6 3 2 3 6 3 2 3 3 6 1 1 6 1 4 6 5 5 5 2 1 6 5 4 2 6 4
 4 6 2 2 1 6 4 5 1 6 4 5 1 4 2 3 3 1 3 4 1 1 3 6 6 4 1 6 3 3 2 2 4 4 5 2 4
 4 3 1 5 1 2 6 3 3 2 4 4 3 2 3 2 4 5 4 2 4 4 4 2 1 4 2 4 3 6 4 2 5 2 2 2 2
 1 6 2 2 4 4 5 2 3 6 2 3 3 3 2 2 3 1 1 2 5 5 5 3 3 2 4 3 4 2 3 2 2 4 1 4 1
 2 5 1 6 5 5 4 3 1 4 4 2 6 3 6 3 2 5 3 2 1 3 2 1 3 6 6 1 5 5 2 5 4 3 4 4 5
 4 1 4 5 6 4 3 1 2 5 5 3 6 5 5 6 2 4 4 2 2 6 4 1 3 5 5 3 2 4 6 2 3 3 4 4 5
 3 5 1 3 5 4 2 3 4 5 1 1 3 2 2 3 2 3 1 4 3 2 4 3 1 4 3 5 3 5 6 4 4 3 4 2 4
 5 1 4 3 5 6 1 5 3 2 6 3 2 4 2 4 6 4 6 2 2 6 1 2 2 1 2 3 1 4 1 2 6 4 6 5 1
 6 1 3 1 4 4 4 2 4 4 5 2 5 6 6 2 4 5 2 2 5 4 2 3 6 6 5 6 4 1 6 2 3 4 2 4 1
 1 4 1 6 1 1 4 2 4 3 3 2 1 3 2 1 2 3 3 5 6 1 3 3 3 3 3 2 2 2 5 5 5 1 5 6 3
 4 1 1 1 1 5 2 1 5 4 4 3 2 3 3 5 6 4 1 2 4 6 6 2 1 6 1 3 2 2 1 2 2 2 6 2 1
 2 6 1 1 2 6 6 3 5 2 5 4 